#!/bin/bash

### Utilities

printHelp() {
  echo "smartive AG kubernetes deployment."
  echo "Prepares all found yaml files and executes a DELETE command on them."
  echo "(does send them into a ./deployment folder and replaces env vars)"
  echo "usage: k8s-delete [basefolder=./k8s/]"
  echo ""
  echo "---"
  echo "Options:"
  echo ""
  echo "basefolder:          starting folder to search for yml files"
  echo ""
}

### Code

# print help and exit if needed
for arg in $@
do
  if [[ $arg = "-h" ]] || [[ $arg = "--help" ]]; then
    printHelp
    exit 0
  fi
done

# set the variables
SOURCE_DIR=$1
SOURCE_DIR=${SOURCE_DIR:-"./k8s/"}
DEST_DIR="./deployment/"

k8s-prepare $SOURCE_DIR $DEST_DIR
kubectl delete -f $DEST_DIR
