#!/bin/bash

### Utilities

printHelp() {
  echo "smartive AG kubernetes deployment preparation."
  echo "Prepares all found yaml files"
  echo "(does send them into a ./deployment folder and replaces env vars)"
  echo "usage: k8s-prepare [basefolder=./k8s/] [deploymentfolder=./deployment/]"
  echo ""
  echo "---"
  echo "Options:"
  echo ""
  echo "basefolder:          starting folder to search for yml files"
  echo "deploymentfolder:    folder to copy the prepared files to"
  echo ""
}

### Code

# print help and exit if needed
for arg in $@
do
  if [[ $arg = "-h" ]] || [[ $arg = "--help" ]]; then
    printHelp
    exit 0
  fi
done

# set the variables
SOURCE_DIR=$1
SOURCE_DIR=${SOURCE_DIR:-"./k8s/"}
DEST_DIR=$2
DEST_DIR=${DEST_DIR:-"./deployment/"}
EXTENSION="yml"

# check for trailing slashes
case "$SOURCE_DIR" in
*/)
    ;;
*)
    SOURCE_DIR="$SOURCE_DIR/"
    ;;
esac

case "$DEST_DIR" in
*/)
    ;;
*)
    DEST_DIR="$DEST_DIR/"
    ;;
esac

if [ ! -d $SOURCE_DIR ]; then
  echo "Source directory does not exist. Aborting."
  exit 1
fi

echo "Moving *.$EXTENSION from $SOURCE_DIR to $DEST_DIR"

if [ -d $DEST_DIR ]; then
  echo "Destination directory already exists, deleting directory."
  rm -rf $DEST_DIR
fi

echo "Creating destination directory"
mkdir -p $DEST_DIR

for file in $(find $SOURCE_DIR -regex ".*\.$EXTENSION$")
do
  name=${file#$SOURCE_DIR}
  name=${name//\//-}
  name=${name#-}
  destFile=$DEST_DIR$name
  echo "Copying $name to $destFile and replace env vars"

  envsubst < "$file" > "$destFile"
done

echo "Done."
