#!/bin/bash

### Utilities

printHelp() {
  echo "smartive AG kubernetes login helper."
  echo "Uses a given variable and creates a kube config that is used."
  echo "The kube config needs to be the whole kube-config file, and must be base64 encoded."
  echo "usage: k8s-login [variablename=KUBE_CONFIG]"
  echo ""
  echo "---"
  echo "Options:"
  echo ""
  echo "variablename:  the name of the environment variable that contains the kube config"
  echo ""
}

### Code

# print help and exit if needed
for arg in $@
do
  if [[ $arg = "-h" ]] || [[ $arg = "--help" ]]; then
    printHelp
    exit 0
  fi
done

# set the variables
CONFIG=$1
CONFIG=${CONFIG:-"KUBE_CONFIG"}

echo "Reading the variable with name '$CONFIG'."

CONFIG=${!CONFIG}

if [ -f $HOME/.kube/config ] ; then
    echo "The kube config ($HOME/.kube/config) already exists."
    read -p "Do you want to proceed and overwrite the file? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        echo "Aborting.."
        exit 1
    fi
fi

echo "Create directory if it does not exist."
mkdir -p $HOME/.kube

echo "Create config file with decoded content."

if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [ "$ID" = "alpine" ]; then
        echo $CONFIG | base64 -d > $HOME/.kube/config
    fi
else
    echo $CONFIG | base64 --decode > $HOME/.kube/config
fi

echo "Done."
