name: Node.js Testing

on:
  push:
    branches:
      - '*'
      - '!master'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run test:ci
        env:
          CI: true
