name: Release Binary

on:
  push:
    branches:
      - master
      - '**' #test.

jobs:
  build_windows:
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            openssl_target: openssl:x64-windows-static-md
    name: Build ${{ matrix.target }} on windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install and setup vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgGitCommitId: b196dacc2f63f37bb75504c36c349042336749cb

      - name: setup openssl
        run: vcpkg install ${{ matrix.openssl_target }}

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/kuby.exe

  build_unix:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    name: Build ${{ matrix.target }} on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/kuby

  build_macos:
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin
    name: Build ${{ matrix.target }} on macos
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/kuby
