name: Release Binary

on:
  push:
    branches:
      - master
      - '**' #test.

jobs:
  build:
    strategy:
      fail-fast: false #test
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows
            target: x86_64-pc-windows-msvc
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # - name: Dependencies Ubuntu
      #   run: sudo apt install -y libssl-dev
      #   if: matrix.os == 'ubuntu-latest'
      # - name: Dependencies macOS
      #   run: brew install openssl
      #   if: matrix.os == 'macos-latest'
      # - name: Dependencies Windows
      #   run: apt install -y libssl-dev
      #   if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/kuby.exe
            target/${{ matrix.target }}/release/kuby
